-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE admission_2 (
    id SERIAL PRIMARY KEY,
    admission_date date,
    discharge_date date,
    patient_id integer
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX admission_2_pkey ON admission_2(id int4_ops);
